## Этап 1. Получение данных

Сначала изучим данные, предоставленные для проекта.

In [299]:
import pandas as pd
import numpy as np

Прочитаем файл phone_tariffs_project.csv и сохраним его в переменной df.

In [347]:
df = pd.read_csv(r'C:/Users/Mariya/PycharmProjects/python-practice-analysis/pandas_practice_project/phone_tariffs_project.csv', sep =';', header = None, names = ['surname', 'name', 'tarif', 'balance', 'age', 'sms', 'voice', 'city', 'phone'])

Получение первых 10 строк таблицы.

In [301]:
df.head(10)

   surname     name       tarif  balance  age  sms  voice     city    phone
0    Girev   Andrey         ВИП     2815   29   58   6358   Moscow   Xiaomi
1    Bykin     Stas  Все за 300     3634   37   78    602    Kazan  Samsung
2   Ivanov     Alex  Всё за 800      410   47   81   3582   Moscow   Huawei
3  Andreev   Sergey  Всё за 500     1981   75   98   5442    Kazan    Apple
4    Girev     Stas  Всё за 800     4969   43   61   8510   Moscow  Samsung
5    Bykin   Andrey  Всё за 500     4308   49   39   2525   Moscow   Xiaomi
6   Kozlov     Igor  Всё за 800      300   60   31   8543  Yakutsk  Samsung
7    Girev     Alex       Промо     4199   47   90   3925    Kazan    Apple
8   Petrov  Nikolay         ВИП     4810   72   88   7188   Moscow    Apple
9  Andreev   Sergey  Всё за 800     4118   52   53    419  Yakutsk    Apple

Общая информация о данных таблицы df.

In [302]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   surname  30 non-null     str
 1   name     30 non-null     str
 2   tarif    30 non-null     str
 3   balance  30 non-null     int64
 4   age      30 non-null     int64
 5   sms      30 non-null     int64
 6   voice    30 non-null     int64
 7   city     30 non-null     str
 8   phone    30 non-null     str
dtypes: int64(4), str(5)
memory usage: 2.2 KB

Рассмотрим полученную информацию подробнее.

Всего в таблице 9 столбцов, типы данных столбцов различны (str или int64)
Количество значений в столбцах одинаково. Это говорит о том, что в данных нет пропусков.

Каждая строка таблицы содержит индивидуальную информацию о пользователе мобильного тарифа: тип тарифа, баланс клиента, возраст клиента, количество отправленных СМС, количество секунд разговора (звонки), город клиента, марка смартфона.

## Этап 2. Проверка данных

Получаем перечень названий столбцов.
Ошибок не обнаружено (например, пробелов, которые могут затруднять доступ к данным)

In [303]:
df.columns

Index(['surname', 'name', 'tarif', 'balance', 'age', 'sms', 'voice', 'city',
       'phone'],
      dtype='str')

Проверим данные на наличие пропусков вызовом набора методов для суммирования пропущенных значений

In [304]:
df.isnull().sum()

surname    0
name       0
tarif      0
balance    0
age        0
sms        0
voice      0
city       0
phone      0
dtype: int64

Необходимо установить наличие дубликатов.

In [305]:
df.duplicated().sum()

np.int64(0)

Вывод

На этапе предобработки в данных ошибок не обнаружилось. Данные корректны и удобны для дальнейшей работы.

## Этап 3. Работа с данными

Вопрос 1: определите средний возраст клиента

In [306]:
result = (np.floor(df['age'].mean()))
f"{result:.0f}"

'48'

Вопрос 2: на каком тарифе средний возраст клиента наименьший

In [307]:
result = (df.groupby('tarif')['age'].mean().idxmin())
result

'Всё за 250 (архив)'

Вопрос 3: из какого города больше всего клиентов?

In [308]:
result = (df.groupby('city')['surname'].count().idxmax())
result

'Moscow'

Вопрос 4: на каком тарифе отправили больше всего СМС?

In [309]:
result = (df.groupby('tarif')['sms'].sum().idxmax())
result

'Всё за 800'

Вопрос 5: определите самую популярную марку смартфона у пользователей до 40 лет (включительно)

In [310]:
result = df['phone'][df['age'] <= 40].max()
result

'Xiaomi'

Вопрос 7: В каком городе клиенты меньше всего отправляют СМС?

In [311]:
result = (df.groupby('city')['sms'].sum().idxmin())
result

'Vladivostok'

Вопрос 8: В каком городе клиенты больше всего говорят по телефону?

In [312]:
result = (df.groupby('city')['voice'].sum().idxmax())
result

'Moscow'

Вопрос 9: Сколько заработала фирма на СМС сообщениях? Стоимость одного сообщения 3 рубля.

In [313]:
result = (df['sms'].sum())*3
result

np.int64(4605)

Вопрос 10: Сколько заработала фирма на СМС сообщениях?

Тарифная сетка:
* ВИП - 1 рубль за СМС
* Все за 300 - 2 рубля за СМС
* Всё за 500 - 3 рубля за СМС
* Всё за 800 - 4 рубля за СМС
* Промо - 7 рублей за СМС
* Корпоративный - 0 рублей за СМС
* Всё за 250 (архив) - 5 рублей за СМС

In [314]:
prices = {'ВИП': 1, 'Все за 300': 2, 'Всё за 500': 3, 'Всё за 800': 4, 'Промо': 7, 'Корпоративный': 0,
         'Всё за 250 (архив)': 5}
result = (df.groupby('tarif')['sms'].sum() * pd.Series(prices)).sum()
result

np.int64(4879)

Вопрос 11: Определите процент клиентов, у которых баланс выше 4000

In [315]:
result = df['balance'][df['balance'] > 4000].count()/(df['balance'].count()) * 100
f"{result:.0f}%"

'30%'

Вопрос 12: Определите процент клиентов, у которых баланс выше 2000 и тариф 'Всё за 500' Ответ округлите вниз.

In [316]:
result = (len(df[(df['balance'] > 2000) & (df['tarif'] == 'Всё за 500')])/len(df)) * 100
f"{(int(result)):.0f}%"

'16%'

Вопрос 13: Сколько клиентов из Москвы, у которых баланс выше 1500 и марка телефона 'Apple'?

In [317]:
result = len(df[(df['balance'] > 1500) & (df['phone'] == 'Apple') & (df['city'] == 'Moscow')])
result

2

Вопрос 14: Самое распространённое имя среди наших клиентов?

In [318]:
result = df['name'].value_counts().idxmax()
print(result)

Sergey

Вопрос 15: Определите процент клиентов у которых телефон Apple и они из Владивостока

In [319]:
result = (len(df[(df['phone'] == 'Apple') & (df['city'] == 'Vladivostok')])/len(df)) * 100
int(result)

3

Вопрос 16: Объедините столбцы surname и name в столбец с именем client_name

In [363]:
df['client_name'] = df['surname'] + ' ' + df['name']
df.head(3)

,surname,name,tarif,balance,age,sms,voice,city,phone,group,client_name
0,Girev,Andrey,ВИП,2409,29,58,6358,Moscow,Xiaomi,B,Girev Andrey
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,B,Bykin Stas
2,Ivanov,Alex,Всё за 800,-400,47,81,3582,Moscow,Huawei,C,Ivanov Alex

Вопрос 17: Поступила задача разбить клиентов на группы
* до 25 лет (включительно) - A (англ. буква)
* с 26 до 40 лет (включительно) - B (англ. буква)
* старше 40 лет - C (англ. буква)

In [349]:
df['group'] = np.where(df['age']<=25,'A',np.where(df['age'] > 40, 'C','B')) # создала новый столбец сразу с присвоенными ему значениями
df.head(3)

  surname    name       tarif  balance  age  sms  voice    city    phone group
0   Girev  Andrey         ВИП     2815   29   58   6358  Moscow   Xiaomi     B
1   Bykin    Stas  Все за 300     3634   37   78    602   Kazan  Samsung     B
2  Ivanov    Alex  Всё за 800      410   47   81   3582  Moscow   Huawei     C

Вопрос 18: Пришла информация, что на сервере в Москве возник сбой и баланс за отправленные смс не списался (у пользователей из Москвы). Спишите с каждого пользователя из Москвы деньги за смс. Количество отправленных смс за которые не списали деньги в столбце sms. Стоимость 1 смс - 3 рубля. (обновите колонку balance)

In [351]:
df['balance'] = np.where(df['city']== 'Moscow', df['balance']-(df['sms'] * 3),df['balance'])
df.head(3)

  surname    name       tarif  balance  age  sms  voice    city    phone group
0   Girev  Andrey         ВИП     2467   29   58   6358  Moscow   Xiaomi     B
1   Bykin    Stas  Все за 300     3634   37   78    602   Kazan  Samsung     B
2  Ivanov    Alex  Всё за 800      -76   47   81   3582  Moscow   Huawei     C

Вопрос 19: На совещании было принято решение детальнее проработать вопрос списания денежных средств. Теперь, спишите деньги (у пользователей из Москвы за смс) с учетом тарифной сетки:

* ВИП - 1 рубль за СМС
* Все за 300 - 2 рубля за СМС
* Всё за 500 - 3 рубля за СМС
* Всё за 800 - 4 рубля за СМС
* Промо - 7 рублей за СМС
* Корпоративный - 0 рублей за СМС
* Всё за 250 (архив) - 5 рублей за СМС

In [352]:
prices = {'ВИП': 1, 'Все за 300': 2, 'Всё за 500': 3, 'Всё за 800': 4, 'Промо': 7, 'Корпоративный': 0,
         'Всё за 250 (архив)': 5}
df['balance'] = np.where(df['city']== 'Moscow', df['balance'] - (df['sms'] * df['tarif'].map(prices)),df['balance'])
df.head(3)

  surname    name       tarif  balance  age  sms  voice    city    phone group
0   Girev  Andrey         ВИП     2409   29   58   6358  Moscow   Xiaomi     B
1   Bykin    Stas  Все за 300     3634   37   78    602   Kazan  Samsung     B
2  Ivanov    Alex  Всё за 800     -400   47   81   3582  Moscow   Huawei     C

Вопрос 20: Пользователь Girev Sergey написал заявление о том, что переехал из города Vladivostok в Kazan.

In [353]:
df.iat[22, 7] = 'Kazan'
df.iat[22, 7]

'Kazan'

Вопрос 21: Измените название колонки balance на client_balance

In [364]:
df.columns = ['surname','name', 'tarif', 'client_balance', 'age', 'sms', 'voice', 'city', 'phone', 'client_name', 'group']
df.head(3)

,surname,name,tarif,client_balance,age,sms,voice,city,phone,client_name,group
0,Girev,Andrey,ВИП,2409,29,58,6358,Moscow,Xiaomi,B,Girev Andrey
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,B,Bykin Stas
2,Ivanov,Alex,Всё за 800,-400,47,81,3582,Moscow,Huawei,C,Ivanov Alex

Вопрос 22: Пересчитайте баланс пользователей в доллары по курсу 1 доллар = 60 рублей. Результат запишите в колонку balance_usd (ответ округлите до двух знаков после запятой).

In [365]:
df['balance_usd'] = (df['client_balance']/60).round(2)
df.head(3)

,surname,name,tarif,client_balance,age,sms,voice,city,phone,client_name,group,balance_usd
0,Girev,Andrey,ВИП,2409,29,58,6358,Moscow,Xiaomi,B,Girev Andrey,40.15
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,B,Bykin Stas,60.57
2,Ivanov,Alex,Всё за 800,-400,47,81,3582,Moscow,Huawei,C,Ivanov Alex,-6.67

Вопрос 23: Высшее руководство компании в ячейке с балансом (в долларах) хотят видеть знак доллара $.

In [382]:
df['balance_usd'] = df['balance_usd'].astype(str) + " $"
df.head(3)

,surname,name,tarif,client_balance,age,sms,voice,city,phone,client_name,group,balance_usd
0,Girev,Andrey,ВИП,2409,29,58,6358,Moscow,Xiaomi,B,Girev Andrey,40.15 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $
1,Bykin,Stas,Все за 300,3634,37,78,602,Kazan,Samsung,B,Bykin Stas,60.57 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $
2,Ivanov,Alex,Всё за 800,-400,47,81,3582,Moscow,Huawei,C,Ivanov Alex,-6.67 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $

Вопрос 24: Расcчитайте долю смс для каждого пользователя. Для этого определите сколько всего было отправлено СМС, а затем расcчитайте отношение отправленных смс клиента к общему количеству. Столбец назовите sms_volume. Оставьте TOP-3

In [328]:
df['sms_volume'] = df['sms']/df['sms'].sum()
result = df.sort_values(by = 'sms_volume', ascending=False).head(3)
result[['surname', 'name', 'sms_volume']].round(3)

    surname    name  sms_volume
3   Andreev  Sergey       0.064
28   Vlasov  Andrey       0.061
7     Girev    Alex       0.059

Вопрос 25: Cредний возраст клиентов из Казани выше чем во Владивостоке? Функция должна вернуть True - если да и False - если нет.

In [329]:
kazan_age = df[df['city'] == 'Kazan']['age'].mean()
vlad_age = df[df['city'] == 'Vladivostok']['age'].mean()
result = kazan_age > vlad_age
result

np.True_

Вопрос 26: Создайте индекс для строк на основе столбцов surname и name. После создания индекса удалите столбцы surname и name

In [383]:
df.index = (df['surname'] + '_' + df['name']).str.upper()
df.drop(['surname','name'], axis = 1, inplace = True)
df.head(3)

,tarif,client_balance,age,sms,voice,city,phone,client_name,group,balance_usd
GIREV_ANDREY,ВИП,2409,29,58,6358,Moscow,Xiaomi,B,Girev Andrey,40.15 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $
BYKIN_STAS,Все за 300,3634,37,78,602,Kazan,Samsung,B,Bykin Stas,60.57 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $
IVANOV_ALEX,Всё за 800,-400,47,81,3582,Moscow,Huawei,C,Ivanov Alex,-6.67 $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $

Вопрос 27: Являются ли лейблы строк уникальными (не повторяющимися)? Верните True - если уникальные и False - если есть дубли.

In [331]:
result = df.index.is_unique
result

False